const wordList = [
  {
    word: "oksigen",
    hint: "Gas tak berwarna, tak berbau, penting untuk hidup.",
  },
  {
    word: "gunung",
    hint: "Ketinggian alami permukaan bumi.",
  },
  {
    word: "kamera",
    hint: "Alat untuk merekam gambar atau video.",
  },
  {
    word: "intan",
    hint: "Permata berkilau dengan kekerasan tinggi.",
  },
  {
    word: "sepeda",
    hint: "Kendaraan beroda dua yang digerakkan manusia.",
  },
  {
    word: "kopi",
    hint: "Minuman berkafein dari biji kopi panggang.",
  },
  {
    word: "tari",
    hint: "Gerakan ritmis tubuh yang diiringi musik.",
  },
  {
    word: "piano",
    hint: "Alat musik dengan tuts dan senar.",
  },
  {
    word: "gurun",
    hint: "Wilayah gersang dengan curah hujan rendah.",
  },
  {
    word: "bulan",
    hint: "Satelit alami Bumi yang bersinar di malam hari.",
  },
  { word: "platform", hint: "Dasar untuk mendukung sesuatu." },
  { word: "ekspresi", hint: "Cara menyampaikan perasaan atau pikiran." },
  { word: "formasi", hint: "Susunan atau pengaturan sesuatu." },
  { word: "pendaki", hint: "Orang yang mendaki gunung." },
  { word: "limpahi", hint: "Memberikan secara melimpah." },
  { word: "produksi", hint: "Proses menghasilkan barang atau jasa." },
  { word: "grafiti", hint: "Lukisan dinding dengan cat semprot." },
  { word: "responi", hint: "Tanggapan terhadap suatu hal." },
  { word: "simpati", hint: "Perasaan turut prihatin terhadap orang lain." },
  { word: "traktor", hint: "Mesin untuk menarik alat berat." },
  { word: "kupasan", hint: "Hasil dari mengupas sesuatu." },
  {
    word: "senjata",
    hint: "Alat yang digunakan untuk menyerang atau bertahan.",
  },
  { word: "pembina", hint: "Orang yang membimbing kelompok tertentu." },
  { word: "kriteria", hint: "Standar yang digunakan untuk menilai sesuatu." },
  { word: "frontal", hint: "Secara langsung atau terang-terangan." },
  { word: "kompas", hint: "Alat penunjuk arah berdasarkan medan magnet." },
  { word: "prinsip", hint: "Aturan atau pedoman dasar." },
  { word: "ventral", hint: "Berhubungan dengan sisi bawah tubuh." },
  { word: "fokuskan", hint: "Mengarahkan perhatian pada satu hal." },
  { word: "menteri", hint: "Pejabat tinggi pemerintahan." },
  { word: "pancaran", hint: "Hasil dari memancarkan cahaya atau energi." },
  { word: "terbitan", hint: "Hasil dari menerbitkan sesuatu." },
  { word: "kapital", hint: "Modal atau aset utama." },
  { word: "kapsul", hint: "Cangkang obat berbentuk silinder." },
  { word: "fundasi", hint: "Dasar dari sebuah bangunan." },
  { word: "pastori", hint: "Tempat tinggal pendeta." },
  { word: "rotasi", hint: "Gerakan memutar pada poros." },
  { word: "posisin", hint: "Letak atau tempat sesuatu berada." },
  { word: "komunal", hint: "Berkaitan dengan masyarakat bersama." },
  { word: "terminal", hint: "Tempat awal atau akhir perjalanan." },
  { word: "karnasi", hint: "Jenis bunga hias dengan warna cerah." },
  { word: "porsini", hint: "Jamur yang sering digunakan untuk memasak." },
  { word: "tantang", hint: "Mengajukan sesuatu untuk dihadapi." },
  {
    word: "kronika",
    hint: "Catatan tentang peristiwa berdasarkan urutan waktu.",
  },
  { word: "diploma", hint: "Dokumen resmi kelulusan pendidikan." },
  { word: "generik", hint: "Bukan bermerek atau umum." },
  { word: "vokalis", hint: "Penyanyi dalam sebuah kelompok musik." },
  { word: "frontal", hint: "Langsung atau tanpa basa-basi." },
  { word: "kartesi", hint: "Berkaitan dengan sistem koordinat matematika." },
  { word: "gitaris", hint: "Orang yang memainkan gitar." },
  { word: "progres", hint: "Kemajuan dalam mencapai sesuatu." },
  { word: "otentik", hint: "Asli dan dapat dipercaya." },
  { word: "analogi", hint: "Persamaan atau kemiripan antar dua hal." },
  { word: "kritisi", hint: "Membahas sesuatu secara mendalam." },
  { word: "virtual", hint: "Berkaitan dengan dunia digital." },
  { word: "mental", hint: "Berkaitan dengan pikiran atau emosi." },
  { word: "optimis", hint: "Sikap selalu melihat sisi baik dari sesuatu." },
  { word: "pendiri", hint: "Orang yang mendirikan sesuatu." },
  { word: "beraksi", hint: "Melakukan suatu tindakan." },
  { word: "kolosal", hint: "Besar dan megah." },
  { word: "karunia", hint: "Pemberian atau hadiah dari Tuhan." },
  { word: "deklare", hint: "Menyatakan secara resmi." },
  { word: "karnasi", hint: "Bunga dengan warna-warna cerah." },
  { word: "organik", hint: "Berasal dari bahan alami." },
  { word: "induksi", hint: "Proses menarik kesimpulan dari fakta tertentu." },
  { word: "federal", hint: "Berkaitan dengan sistem pemerintahan." },
  { word: "nirmala", hint: "Bersih atau tanpa cela." },
  { word: "terminal", hint: "Tempat pemberhentian transportasi." },
  { word: "generis", hint: "Khas atau unik." },
  { word: "minimal", hint: "Yang paling kecil atau sedikit." },
  { word: "aksesor", hint: "Pelengkap atau tambahan." },
  { word: "komunis", hint: "Penganut ideologi komunis." },
  { word: "milenia", hint: "Periode seribu tahun." },
  { word: "sistemik", hint: "Berkaitan dengan keseluruhan sistem." },
  { word: "ekonomi", hint: "Ilmu yang mempelajari pengelolaan sumber daya." },
  { word: "kapelan", hint: "Pemimpin agama dalam komunitas kecil." },
  { word: "komuter", hint: "Orang yang bepergian secara rutin." },
  { word: "diploma", hint: "Dokumen kelulusan dari institusi pendidikan." },
  { word: "frontal", hint: "Terbuka tanpa basa-basi." },
  { word: "terminal", hint: "Pusat pemberhentian transportasi." },
  { word: "kanalis", hint: "Pengarah aliran air atau saluran." },
  { word: "lokalis", hint: "Orang yang mendukung hal-hal setempat." },
  { word: "matriks", hint: "Susunan angka dalam bidang matematika." },
  { word: "faktual", hint: "Berdasarkan fakta atau kenyataan." },
  { word: "otentik", hint: "Asli dan dapat dipercaya." },
  { word: "ekspres", hint: "Cepat dan tidak lambat." },
  { word: "traktor", hint: "Kendaraan untuk mengolah lahan." },
  { word: "kreatif", hint: "Penuh daya cipta dan inovasi." },
  { word: "terminal", hint: "Pemberhentian transportasi." },
  { word: "kristal", hint: "Benda padat dengan susunan atom teratur." },
  { word: "rebahan", hint: "Aktivitas santai sambil berbaring." },
  { word: "santuy", hint: "Sikap santai tanpa beban." },
  { word: "ngabers", hint: "Sebutan untuk penggemar ngabuburit." },
  { word: "julid", hint: "Sikap suka mengomentari orang lain." },
  { word: "bucin", hint: "Budak cinta, orang yang sangat cinta." },
  { word: "gabut", hint: "Kondisi bosan tanpa kegiatan." },
  { word: "mager", hint: "Malas gerak atau tidak ingin bergerak." },
  { word: "healing", hint: "Aktivitas untuk menyegarkan pikiran." },
  { word: "gibah", hint: "Membicarakan orang lain di belakangnya." },
  { word: "vibes", hint: "Suasana atau perasaan tertentu." },
  { word: "ghosting", hint: "Menghilang tanpa penjelasan dalam hubungan." },
  { word: "flexing", hint: "Memamerkan sesuatu untuk menarik perhatian." },
  { word: "kuy", hint: "Ajakannya terbalik dari 'yuk'." },
  { word: "panik", hint: "Reaksi gugup atau ketakutan." },
  { word: "seru", hint: "Menggambarkan sesuatu yang menyenangkan." },
  { word: "slow", hint: "Santai tanpa tergesa-gesa." },
  { word: "ciyus", hint: "Bahasa gaul untuk 'serius'." },
  { word: "lebay", hint: "Berlebihan atau dramatis." },
  { word: "rempong", hint: "Ribet atau banyak urusan." },
  { word: "ngegas", hint: "Sikap cepat marah atau reaktif." },
  { word: "pansos", hint: "Cari perhatian di media sosial." },
  { word: "jokes", hint: "Candaan untuk menghibur orang lain." },
  { word: "auto", hint: "Segala sesuatu yang langsung terjadi." },
  { word: "ngeprank", hint: "Membuat lelucon pada orang lain." },
  { word: "spill", hint: "Mengungkap rahasia atau informasi." },
  { word: "crush", hint: "Orang yang diam-diam disukai." },
  { word: "noob", hint: "Sebutan untuk pemula atau amatir." },
  { word: "savage", hint: "Sikap keren tanpa basa-basi." },
  { word: "bros", hint: "Sebutan akrab untuk teman pria." },
  { word: "thrift", hint: "Belanja barang bekas berkualitas." },
  { word: "vlog", hint: "Video log tentang aktivitas sehari-hari." },
  { word: "hype", hint: "Popularitas sesuatu di masa kini." },
  { word: "update", hint: "Informasi terbaru tentang sesuatu." },
  { word: "random", hint: "Tidak terduga atau tanpa pola." },
  { word: "relax", hint: "Beristirahat untuk menghilangkan stres." },
  { word: "glowup", hint: "Transformasi menjadi lebih baik." },
  { word: "drama", hint: "Cerita penuh emosi dan konflik." },
  { word: "tiktok", hint: "Platform media sosial berbasis video pendek." },
  { word: "login", hint: "Proses masuk ke dalam akun." },
  { word: "viral", hint: "Menyebar dengan cepat di internet." },
  { word: "filter", hint: "Efek yang digunakan pada foto atau video." },
  { word: "squad", hint: "Kelompok atau geng teman dekat." },
  { word: "selfie", hint: "Foto diri sendiri menggunakan kamera." },
  { word: "scroll", hint: "Melihat layar ke atas atau bawah." },
  { word: "chill", hint: "Bersantai dengan tenang." },
  { word: "emoji", hint: "Simbol ekspresi di pesan digital." },
  { word: "gaming", hint: "Bermain video game secara aktif." },
  { word: "drinks", hint: "Minuman modern seperti kopi susu." },
  { word: "layout", hint: "Tata letak untuk tampilan." },
  { word: "remake", hint: "Pembuatan ulang sesuatu dengan versi baru." },
  { word: "server", hint: "Komputer yang menyediakan layanan digital." },
  { word: "coding", hint: "Proses menulis program komputer." },
  { word: "online", hint: "Terhubung ke jaringan internet." },
  { word: "backup", hint: "Cadangan data untuk keamanan." },
  { word: "stream", hint: "Menonton langsung tanpa diunduh." },
  { word: "swag", hint: "Gaya keren dan percaya diri." },
  { word: "promo", hint: "Penawaran khusus untuk pembeli." },
  { word: "bot", hint: "Program otomatis yang menjalankan tugas." },
  { word: "like", hint: "Tanda suka pada media sosial." },
  { word: "notif", hint: "Pemberitahuan digital tentang sesuatu." },
  { word: "admin", hint: "Pengelola grup atau akun online." },
  { word: "fake", hint: "Tidak asli atau palsu." },
  { word: "unbox", hint: "Membuka paket dan menunjukkan isinya." },
  { word: "status", hint: "Unggahan singkat di media sosial." },
  { word: "banjir", hint: "Kondisi penuh akibat terlalu banyak hal." },
  { word: "dmpls", hint: "Direct message please, chat pribadi." },
  { word: "salty", hint: "Kesal atau tidak senang." },
  { word: "swipe", hint: "Geser layar pada ponsel atau tablet." },
  { word: "reply", hint: "Balasan terhadap pesan atau komentar." },
  { word: "baper", hint: "Bawa perasaan atau terlalu sensitif." },
  { word: "stay", hint: "Tetap bertahan di suatu tempat." },
  { word: "intro", hint: "Pengantar untuk sesuatu yang baru." },
  { word: "boost", hint: "Meningkatkan sesuatu dengan cepat." },
  { word: "merge", hint: "Menggabungkan dua hal menjadi satu." },
  { word: "frame", hint: "Bingkai untuk foto atau gambar." },
  { word: "logis", hint: "Bersifat masuk akal atau rasional." },
  { word: "pixel", hint: "Unit terkecil pada layar digital." },
  { word: "trend", hint: "Hal yang sedang populer di kalangan masyarakat." },
  { word: "cash", hint: "Pembayaran dengan uang tunai." },
  { word: "group", hint: "Kumpulan orang dengan tujuan yang sama." },
  { word: "phone", hint: "Gadget untuk komunikasi dan hiburan." },
  { word: "click", hint: "Menekan tombol pada perangkat elektronik." },
  { word: "error", hint: "Kesalahan pada sistem atau perangkat." },
  { word: "jamet", hint: "Jawa metal, istilah untuk gaya tertentu." },
];
